### ISSUE TITLE
Implementation of the exception handler

### ISSUE THREAD

**Issue by PanasyukVA** [TaskManagementSystemCourses/TaskManagmentSystem#12]
Estimate ? days

**Comment by GINomad** [comment]
Реализовать ErrorController с методами для каждого типа ошибок(как минимум коды 500, 403,404).
Реализовать View для разных типов ошибок.
Перехват  и обработку выполнить в Applictaion_Error(Global.asax)

Дополнительно:
Можно впихнуть имейл оповещение админа о возникшей ошибке или вести лог. Реализацию выполнить в контроллере.
