### ISSUE TITLE
Implementation of an authorization

### ISSUE THREAD

**Issue by PanasyukVA** [TaskManagementSystemCourses/TaskManagmentSystem#7]
Estimate 7 days

**Comment by dpvnbd** [comment]
1. Изучить механизм авторизации в Identity framework (4 часа)
2. Продумать и создать набор ролей для пользователей приложения (2 часа)
3. Повесить ограничения на некоторые действия в зависимости от роли (4 часа)
4. Создать страницу управления ролями пользователей (6 часов)

**Comment by dpvnbd** [comment]
![](http://i.imgur.com/5qZw5WO.png)
