### ISSUE TITLE
Adding the "Send email" functionality to the project

### ISSUE THREAD

**Issue by PanasyukVA** [TaskManagementSystemCourses/TaskManagmentSystem#8]
Estimate 4 days

**Comment by dpvnbd** [comment]
1. Исследование возможности отправки при помощи Identity framework (1 час)
2. Выбор smtp-сервера и создание аккаунта для приложения (1 час)
3. Реализация сервиса отправки сообщений (2 часа)
4. Формирование разных типов сообщений по шаблонам (2 часа)
5. Реализация пользовательской настройки отправки сообщений (1 час)
6. Добавить отправку сообщений при некоторых действиях (2 часа)
9 часов ~ 3 дня
